version: "3.9"

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      # MYSQL_USER: volodb
      # MYSQL_PASSWORD: Sonne1234
      MYSQL_DATABASE: volo_db
    volumes:
      - ~/mysql/volodb:/var/lib/mysql
    ports:
      - "40101:3306"
    networks:
      - spring-mysql-network

  api:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - TAG_NAME=volodb_api
    ports:
      - 40102:8080
    container_name: volodb_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/volo_db
    #   SPRING_DATASOURCE_USERNAME: your_database_user
    #   SPRING_DATASOURCE_PASSWORD: your_database_password
    depends_on:
      - mysql_db
    networks:
      - spring-mysql-network

networks:
  spring-mysql-network:
    driver: bridge
