version: "3.9"

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      # MYSQL_USER: volodb
      # MYSQL_PASSWORD: Sonne1234
      MYSQL_DATABASE: volo_db
    volumes:
      - ~/mysql/volodb:/var/lib/mysql
    ports:
      - "40101:3306"
    networks:
      volodb-network:
        ipv4_address: 192.168.0.11

  minio_obj_store:
    image: quay.io/minio/minio
    container_name: minio_obj_store
    environment:
      MINIO_ROOT_USER: volodb
      MINIO_ROOT_PASSWORD: test1234
    volumes:
      - ~/minio/volodb/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      volodb-network:
        ipv4_address: 192.168.0.13

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TAG_NAME=volodb_api
    ports:
      - 40102:8080
    container_name: volodb_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/volo_db
    #   SPRING_DATASOURCE_USERNAME: your_database_user
    #   SPRING_DATASOURCE_PASSWORD: your_database_password
    depends_on:
      - mysql_db
    networks:
      volodb-network:
        ipv4_address: 192.168.0.12

networks:
  volodb-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
