version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: volo_db
    volumes:
      - ~/mysql/volodb:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - volodb_network

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ~/minio/volodb/data:/data
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    command: server /data --console-address ":9001"
    networks:
      - volodb_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TAG_NAME=volodb_api
    ports:
      - ${API_PORT}:8080
    container_name: volodb_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:${MYSQL_PORT}/volo_db
    depends_on:
      - mysql
      - minio
    networks:
      - volodb_network

networks:
  volodb_network:
    name: volodb_network
