application:
  formatted-version: "0.0.1"
  title: "VoloDB"

#
# JDBC properties
#
spring:
  main:
    banner-mode: "log"
  banner:
    location: "banner.txt"
  datasource:
    url: "jdbc:mysql://localhost:3306/volo_db"
    username: root
    password: test1234

  jpa:
    hibernate:
      naming-strategy: "org.hibernate.cfg.EJB3NamingStrategy"
#
# SEECURITY
#
security:
  jwt:
    secret-key: "dasisteinsehrlangerabersinnlosersecretkeydenmanichterratensoll"
    token-duration: 1H
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          cors: DEBUG
#
# BANNER
#
