name: DockerProd Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Docker Compose
        run: |
          sudo docker compose down
          sudo docker compose up
