name: DockerProd Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy with Docker Compose
        uses: isbang/compose-action@v1.5.1
