name: DockerProd Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Deploy via Docker
        run: |
          docker compose down
          docker compose up -d
